apiVersion: v1
kind: Service
metadata:
  name: eks-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: eks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks
  labels:
    app: eks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks
  template:
    metadata:
      labels:
        app: eks
    spec:
      containers:
      - name: eks
        image: REPOSITORY_URI
        ports:
        - containerPort: 80
        imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
